config-version: 1

# Many of these options are set by deffault; however, you can fully customize the pickaxe using in-game commands: /pico3x3 <jugador|reload> [material] [radius] [break-depth(true/false)] [encantamiento] [nivel]

pickaxe:
  material: NETHERITE_PICKAXE
  
  radius: 1

  break-depth: true

  name: '&6&lSUPER PICO {area}'
  
  lore:
    - '&7--------------------------'
    - '&eHabilidad Especial:'
    - '&fRompe bloques en un área &b{area}'
    - '&7--------------------------'
    
  prevent-bedrock-break: true

command:

  op-only: true

worldguard:

  allow-unset-block-break: true

# You can customize some of the plugin's messages in this section
messages:
  only-player: '&cEste comando solo puede usarse desde el juego.'
  no-op: '&cNo tienes permiso. Solo los administradores con OP pueden usar este comando.'
  give: '&a¡Has recibido el Pico Legendario {area}!'
  cannot-break-bedrock: '&c¡Cuidado! Este pico no tiene el poder para romper Bedrock.'
  reload: '&a[Supreme Pickaxe 3x3] La configuración ha sido recargada con éxito.'
